//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Using_EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Teacher
    {
        public int TeacherID { get; set; }
        public string Teacher_Name { get; set; }
        public string Contact { get; set; }
        public string Qualifcation { get; set; }
    }
}
